name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile

      - name: Build
        run: yarn build
